### ISSUE TITLE
sass gem is required to build examples

### ISSUE THREAD

**Issue by tarnacious** [mtr/core-layout#18]
Hi,

I had to install the sass gem manually to build the examples, should this have been installed by NPM?

Thanks

**Comment by mtr** [comment]
@tarnacious: I am sorry, but since the procedure for installing the `sass` gem differs from one OS to another, I am unsure of if–and how–`npm` should be configured to install it automatically.

However, based on your feedback, I've added a new section to the [README.md](https://github.com/mtr/core-layout/blob/bb530c773e678bb8901971d77c4d0c87fe18339d/README.md) about the necessity of install the `sass` gem before building the demo.

Thank you for your feedback.
